import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { compile, type JSONSchema } from 'json-schema-to-typescript';
import { definitions, JSON_SCHEMA_DIALECT, schemaDocument, schemaNames } from '../src/schemas.js';
import { checkOpenApi, generateOpenApi } from '../src/openapi.js';

const generatedSchema = {
  $schema: JSON_SCHEMA_DIALECT,
  title: 'ContractTypes',
  type: 'object',
  properties: Object.fromEntries(schemaNames.map((name) => [name, { $ref: `#/$defs/${name}` }])),
  required: schemaNames,
  additionalProperties: false,
  $defs: schemaDocument.$defs,
};
const types = await compile(generatedSchema as unknown as JSONSchema, 'ContractTypes', {
  bannerComment: '/* Generated by scripts/generate.ts from src/schemas.ts. DO NOT EDIT. */',
  additionalProperties: false,
  unknownAny: true,
  declareExternallyReferenced: true,
  maxItems: 0,
  style: { singleQuote: true, semi: true, trailingComma: 'all', printWidth: 100 },
});
const openapi = generateOpenApi();
const problems = checkOpenApi(openapi);
if (problems.length > 0) throw new Error(problems.join('\n'));

const artifacts = [
  ['../src/generated.ts', types],
  ['../openapi/openapi.json', `${JSON.stringify(openapi, null, 2)}\n`],
  ['../openapi/contracts.schema.json', `${JSON.stringify({ ...schemaDocument, $defs: Object.fromEntries(schemaNames.map((name) => [name, { title: name, ...definitions[name] }])) }, null, 2)}\n`],
] as const;
const check = process.argv.includes('--check');
for (const [relative, content] of artifacts) {
  const path = fileURLToPath(new URL(relative, import.meta.url));
  if (check) {
    const actual = await readFile(path, 'utf8').catch(() => '');
    if (actual !== content) throw new Error(`Generated artifact is stale: ${relative}. Run pnpm --filter @imbox/contracts generate.`);
  } else {
    await writeFile(path, content);
  }
}
