/** Action authority is modeled separately from permission to read a Task. */
const ref = (name: string) => ({ $ref: `#/$defs/${name}` });
const str = (maxLength: number, minLength = 1) => ({ type: 'string', minLength, maxLength });
const obj = (properties: Record<string, unknown>, required = Object.keys(properties)) => ({
  type: 'object',
  properties,
  required,
  additionalProperties: false,
});
const arr = (items: unknown, maxItems: number, minItems = 0) => ({
  type: 'array',
  items,
  maxItems,
  minItems,
});
const en = (...values: string[]) => ({ type: 'string', enum: values });
const fingerprint = { ...str(64, 64), pattern: '^[a-f0-9]{64}$' };
const view = {
  view_scope: ref('Identifier'),
  authz_generation: ref('Version'),
  projection_id: ref('Identifier'),
  projection_revision: ref('Version'),
};
export const actionDefinitions = {
  ActionResourceRef: {
    oneOf: [
      ref('TaskVersionRef'),
      obj({
        type: { type: 'string', const: 'artifact_version' },
        id: ref('Identifier'),
        version: ref('Version'),
        sha256: fingerprint,
      }),
    ],
  },
  PublicationSourceParams: obj({ id: ref('Identifier'), versionId: ref('Identifier') }),
  PublicationSource: obj({ reference: ref('ActionResourceRef'), text: str(4000) }),
  ActionParameters: obj({ text: str(4000) }),
  CreateGrantInput: obj({
    task_id: ref('Identifier'),
    executor_principal_id: ref('Identifier'),
    tool_id: str(100),
    tool_version: ref('Version'),
    target_id: str(100),
    allow_execute: { type: 'boolean' },
    allow_disclosure: { type: 'boolean' },
    resource_versions: arr(ref('ActionResourceRef'), 20),
    approver_principal_ids: { ...arr(ref('Identifier'), 20, 1), uniqueItems: true },
    budget: ref('InitialBudget'),
    expires_at: ref('UtcTimestamp'),
  }),
  CapabilityGrant: obj({
    id: ref('Identifier'),
    task_id: ref('Identifier'),
    executor_principal_id: ref('Identifier'),
    issued_by: ref('Identifier'),
    tool_id: str(100),
    tool_version: ref('Version'),
    target_id: str(100),
    allow_execute: { type: 'boolean' },
    allow_disclosure: { type: 'boolean' },
    resource_versions: arr(ref('ActionResourceRef'), 20),
    approver_principal_ids: arr(ref('Identifier'), 20),
    budget: ref('InitialBudget'),
    status: en('active', 'revoked'),
    revision: ref('Version'),
    expires_at: ref('UtcTimestamp'),
    created_at: ref('UtcTimestamp'),
  }),
  CapabilityGrantPage: obj({ items: arr(ref('CapabilityGrant'), 200) }),
  CreateActionInput: obj(
    {
      task_id: ref('Identifier'),
      grant_id: ref('Identifier'),
      executor_principal_id: ref('Identifier'),
      tool_id: str(100),
      tool_version: ref('Version'),
      target_id: str(100),
      parameters: ref('ActionParameters'),
      resource_versions: arr(ref('ActionResourceRef'), 20),
      business_key: ref('IdempotencyKey'),
      estimate: ref('InitialBudget'),
      required: { type: 'boolean' },
    },
    [
      'task_id',
      'grant_id',
      'executor_principal_id',
      'tool_id',
      'tool_version',
      'target_id',
      'parameters',
      'resource_versions',
      'business_key',
      'estimate',
    ],
  ),
  ReviseActionInput: obj({
    parameters: ref('ActionParameters'),
    resource_versions: arr(ref('ActionResourceRef'), 20),
  }),
  ActionApprovalDecisionInput: obj({
    decision: en('approve', 'reject'),
    action_version: ref('Version'),
    fingerprint,
    comment: str(2000),
  }),
  ActionApproval: obj(
    {
      id: ref('Identifier'),
      action_id: ref('Identifier'),
      action_version: ref('Version'),
      fingerprint,
      target_id: str(100),
      status: en('pending', 'approved', 'rejected', 'revoked'),
      expires_at: ref('UtcTimestamp'),
      decided_by: ref('Identifier'),
      consumed: { type: 'boolean' },
    },
    [
      'id',
      'action_id',
      'action_version',
      'fingerprint',
      'target_id',
      'status',
      'expires_at',
      'consumed',
    ],
  ),
  Action: obj(
    {
      id: ref('Identifier'),
      task_id: ref('Identifier'),
      requester_id: ref('Identifier'),
      executor_id: ref('Identifier'),
      grant_id: ref('Identifier'),
      grant_revision: ref('Version'),
      tool_id: str(100),
      tool_version: ref('Version'),
      target_id: str(100),
      parameters: ref('ActionParameters'),
      content_restricted: { type: 'boolean' },
      resource_versions: arr(ref('ActionResourceRef'), 20),
      business_key: ref('IdempotencyKey'),
      fingerprint,
      status: en(
        'proposed',
        'awaiting_approval',
        'ready',
        'executing',
        'succeeded',
        'failed',
        'unknown',
        'cancelled',
      ),
      version: ref('Version'),
      approval_binding_version: ref('Version'),
      approval_required: { type: 'boolean' },
      required: { type: 'boolean' },
      attempt_count: { type: 'integer', minimum: 0, maximum: 100 },
      estimate: ref('InitialBudget'),
      approval: ref('ActionApproval'),
      created_at: ref('UtcTimestamp'),
      ...view,
    },
    [
      'id',
      'task_id',
      'requester_id',
      'executor_id',
      'grant_id',
      'grant_revision',
      'tool_id',
      'tool_version',
      'target_id',
      'parameters',
      'resource_versions',
      'business_key',
      'fingerprint',
      'status',
      'version',
      'approval_binding_version',
      'approval_required',
      'required',
      'attempt_count',
      'estimate',
      'created_at',
      ...Object.keys(view),
    ],
  ),
  ActionPage: obj({ items: arr(ref('Action'), 200), next_cursor: ref('Cursor') }, ['items']),
  ActionReconcileInput: obj({ reason: str(2000) }),
  ActionReconciliation: obj({
    action: ref('Action'),
    outcome: en('succeeded', 'no_effect', 'unknown', 'conflict'),
  }),
};
