/* Generated by scripts/generate.ts from src/schemas.ts. DO NOT EDIT. */

export type Identifier = string;
export type UtcTimestamp = string;
export type Version = string;
export type Cursor = string;
export type IdempotencyKey = string;
export type Counter = string;
export type ArtifactCommentAnchor =
  | {
      type: 'whole';
    }
  | {
      type: 'text_range';
      start: number;
      end: number;
    };
export type TaskRunOrigin =
  | {
      access: 'none';
    }
  | {
      access: 'restricted';
    }
  | {
      access: 'available';
      run_id: Identifier;
      run_version: Version;
      conversation_id: Identifier;
      context_manifest_id: Identifier;
      created_at: UtcTimestamp;
    };
export type ModelToolDecision =
  | {
      kind: 'final';
      text: string;
    }
  | {
      kind: 'tool_intent';
      text: string;
    };
export type RuntimeSourceReference =
  | {
      type: 'message' | 'task';
      id: Identifier;
      version: Version;
      required: boolean;
    }
  | {
      type: 'memory' | 'artifact_version';
      id: Identifier;
      version: Version;
      required: boolean;
      sha256: string;
    };
export type EvidenceInput = TextEvidenceInput | ArtifactEvidenceRef;
export type Evidence = TextEvidence | ArtifactEvidenceRef;
export type WsClientFrame = WsHello | WsSubscribe | WsAck | WsHeartbeat;
export type WsServerFrame = WsWelcome | WsSubscribed | WsControl | WsHeartbeat | ProjectionEnvelope;

export interface ContractTypes {
  OrganizationInvitationPreview: OrganizationInvitationPreview;
  OrganizationInvitation: OrganizationInvitation;
  OrganizationInvitationPage: OrganizationInvitationPage;
  CreateOrganizationInvitationInput: CreateOrganizationInvitationInput;
  CreatedOrganizationInvitation: CreatedOrganizationInvitation;
  RevokeOrganizationInvitationInput: RevokeOrganizationInvitationInput;
  AcceptOrganizationInvitationInput: AcceptOrganizationInvitationInput;
  AcceptedOrganizationInvitation: AcceptedOrganizationInvitation;
  ManagedTenantMember: ManagedTenantMember;
  ManagedTenantMemberPage: ManagedTenantMemberPage;
  SetTenantMemberInput: SetTenantMemberInput;
  OrganizationManagementAccess: OrganizationManagementAccess;
  ManagedWorkspace: ManagedWorkspace;
  ManagedWorkspacePage: ManagedWorkspacePage;
  OrganizationCandidate: OrganizationCandidate;
  OrganizationCandidatePage: OrganizationCandidatePage;
  ManagedWorkspaceMember: ManagedWorkspaceMember;
  ManagedWorkspaceMemberPage: ManagedWorkspaceMemberPage;
  CreateManagedWorkspaceInput: CreateManagedWorkspaceInput;
  SetWorkspaceMemberInput: SetWorkspaceMemberInput;
  MemorySourceRef: MemorySourceRef;
  CreateMemoryInput: CreateMemoryInput;
  UpdateMemoryInput: UpdateMemoryInput;
  ExplicitMemory: ExplicitMemory;
  ExplicitMemoryPage: ExplicitMemoryPage;
  MemoryDeletion: MemoryDeletion;
  KnowledgeSearchHit: KnowledgeSearchHit;
  KnowledgeSearchPage: KnowledgeSearchPage;
  KnowledgeSearchQuery: KnowledgeSearchQuery;
  RecoveryReasonInput: RecoveryReasonInput;
  RecoveryLookupInput: RecoveryLookupInput;
  RecoveryConfirmInput: RecoveryConfirmInput;
  RecoveryUnfreezeInput: RecoveryUnfreezeInput;
  RecoveryStatus: RecoveryStatus;
  RecoveryIntent: RecoveryIntent;
  RecoveryEvidence: RecoveryEvidence;
  RecoveryCase: RecoveryCase;
  RecoveryCasePage: RecoveryCasePage;
  NotificationPushKey: NotificationPushKey;
  NotificationSubscription: NotificationSubscription;
  NotificationItem: NotificationItem;
  NotificationPage: NotificationPage;
  NotificationUnread: NotificationUnread;
  NotificationLocation: NotificationLocation;
  NotificationRead: NotificationRead;
  NotificationPreferences: NotificationPreferences;
  NotificationPreferencesInput: NotificationPreferencesInput;
  NotificationMuteInput: NotificationMuteInput;
  NotificationMute: NotificationMute;
  NotificationDeviceInput: NotificationDeviceInput;
  NotificationDevice: NotificationDevice;
  NotificationDevicePage: NotificationDevicePage;
  CreateExportInput: CreateExportInput;
  ExportJob: ExportJob;
  GovernancePolicy: GovernancePolicy;
  ArtifactCommentAnchor: ArtifactCommentAnchor;
  CreateArtifactCommentInput: CreateArtifactCommentInput;
  EditArtifactCommentInput: EditArtifactCommentInput;
  ArtifactComment: ArtifactComment;
  ArtifactCommentPage: ArtifactCommentPage;
  CreateArtifactShareInput: CreateArtifactShareInput;
  ArtifactShare: ArtifactShare;
  ArtifactShareRevocation: ArtifactShareRevocation;
  ArtifactShareSummary: ArtifactShareSummary;
  ArtifactSharePage: ArtifactSharePage;
  ArtifactCommentDeletion: ArtifactCommentDeletion;
  PromoteRunInput: PromoteRunInput;
  TaskRunOrigin: TaskRunOrigin;
  CursorOnlyQuery: CursorOnlyQuery;
  TaskEscalation: TaskEscalation;
  TaskEscalationPage: TaskEscalationPage;
  CreateScheduleInput: CreateScheduleInput;
  ReviseScheduleInput: ReviseScheduleInput;
  Schedule: Schedule;
  ScheduleList: ScheduleList;
  ScheduleOccurrence: ScheduleOccurrence;
  ScheduleOccurrenceList: ScheduleOccurrenceList;
  ResourceScopeQuery: ResourceScopeQuery;
  StoredResourcePage: StoredResourcePage;
  StoredArtifactPage: StoredArtifactPage;
  CreateUploadInput: CreateUploadInput;
  UploadTicket: UploadTicket;
  StoredResource: StoredResource;
  CreateStoredArtifactInput: CreateStoredArtifactInput;
  CreateArtifactBranchInput: CreateArtifactBranchInput;
  MergeArtifactBranchInput: MergeArtifactBranchInput;
  ArtifactBranch: ArtifactBranch;
  ArtifactBranchPage: ArtifactBranchPage;
  CreateStoredArtifactVersionInput: CreateStoredArtifactVersionInput;
  StoredArtifact: StoredArtifact;
  StoredArtifactVersion: StoredArtifactVersion;
  StoredArtifactVersionPage: StoredArtifactVersionPage;
  ResourceDeletion: ResourceDeletion;
  AgentManagementAccess: AgentManagementAccess;
  AgentCredentialPage: AgentCredentialPage;
  AgentDeliveryInput: AgentDeliveryInput;
  AgentDeliveryReceipt: AgentDeliveryReceipt;
  RegisterAgentInput: RegisterAgentInput;
  RegisteredAgent: RegisteredAgent;
  AgentDirectory: AgentDirectory;
  AgentDirectoryQuery: AgentDirectoryQuery;
  IssueAgentCredentialInput: IssueAgentCredentialInput;
  AgentCredential: AgentCredential;
  IssuedAgentCredential: IssuedAgentCredential;
  MachineTokenInput: MachineTokenInput;
  MachineToken: MachineToken;
  MachineLease: MachineLease;
  MachineClaim: MachineClaim;
  MachineHeartbeatInput: MachineHeartbeatInput;
  MachineHeartbeat: MachineHeartbeat;
  MachineCancellationAckInput: MachineCancellationAckInput;
  MachineCancellationAck: MachineCancellationAck;
  MachineReportInput: MachineReportInput;
  MachineRunPage: MachineRunPage;
  ActionParameters: ActionParameters;
  CreateGrantInput: CreateGrantInput;
  CapabilityGrant: CapabilityGrant;
  CapabilityGrantPage: CapabilityGrantPage;
  CreateActionInput: CreateActionInput;
  ReviseActionInput: ReviseActionInput;
  ActionApprovalDecisionInput: ActionApprovalDecisionInput;
  ActionApproval: ActionApproval;
  Action: Action;
  ActionPage: ActionPage;
  ActionReconcileInput: ActionReconcileInput;
  ActionReconciliation: ActionReconciliation;
  ModelToolDecision: ModelToolDecision;
  MachineToolIntentInput: MachineToolIntentInput;
  MachineToolExecuteInput: MachineToolExecuteInput;
  RuntimeRunPage: RuntimeRunPage;
  RuntimeRunListQuery: RuntimeRunListQuery;
  RuntimeSourceReference: RuntimeSourceReference;
  InstallRuntimeAgentInput: InstallRuntimeAgentInput;
  RuntimeAgentInstallation: RuntimeAgentInstallation;
  CreateRuntimeRunInput: CreateRuntimeRunInput;
  RuntimeBudget: RuntimeBudget;
  RuntimeRun: RuntimeRun;
  RuntimeContextItem: RuntimeContextItem;
  RuntimeContextManifest: RuntimeContextManifest;
  Identifier: Identifier;
  Version: Version;
  Counter: Counter;
  UtcTimestamp: UtcTimestamp;
  Cursor: Cursor;
  IdempotencyKey: IdempotencyKey;
  PaginationQuery: PaginationQuery;
  ResourceParams: ResourceParams;
  ProjectionContext: ProjectionContext;
  Principal: Principal;
  Workspace: Workspace;
  WorkspacePage: WorkspacePage;
  DevLoginInput: DevLoginInput;
  DevLoginResult: DevLoginResult;
  Session: Session;
  Account: Account;
  Me: Me;
  WorkspaceMemberPage: WorkspaceMemberPage;
  ConversationMemberPage: ConversationMemberPage;
  AddConversationMemberInput: AddConversationMemberInput;
  ReactionInput: ReactionInput;
  MessageReactionSummary: MessageReactionSummary;
  MessageQuote: MessageQuote;
  ReactionPage: ReactionPage;
  ReadCursorInput: ReadCursorInput;
  ReadCursor: ReadCursor;
  Error: Error;
  CreateConversationInput: CreateConversationInput;
  Conversation: Conversation;
  CreateMessageInput: CreateMessageInput;
  EditMessageInput: EditMessageInput;
  Message: Message;
  ConversationPage: ConversationPage;
  MessagePage: MessagePage;
  Budget: Budget;
  TaskVersionRef: TaskVersionRef;
  TextEvidenceInput: TextEvidenceInput;
  ArtifactEvidenceRef: ArtifactEvidenceRef;
  EvidenceInput: EvidenceInput;
  TextEvidence: TextEvidence;
  Evidence: Evidence;
  InitialBudget: InitialBudget;
  CreateTaskInput: CreateTaskInput;
  UpdateTaskInput: UpdateTaskInput;
  TaskParticipantInput: TaskParticipantInput;
  TaskParticipantPage: TaskParticipantPage;
  TaskReasonInput: TaskReasonInput;
  ReopenTaskInput: ReopenTaskInput;
  TaskStateInput: TaskStateInput;
  TaskConversationLinkInput: TaskConversationLinkInput;
  TaskSummary: TaskSummary;
  TaskSummaryPage: TaskSummaryPage;
  TaskDependencyInput: TaskDependencyInput;
  WorkProposal: WorkProposal;
  CreateTaskRequestInput: CreateTaskRequestInput;
  ReviseTaskRequestInput: ReviseTaskRequestInput;
  SubmissionInput: SubmissionInput;
  Submission: Submission;
  SubmissionPage: SubmissionPage;
  TaskReviewInput: TaskReviewInput;
  TaskReview: TaskReview;
  TaskReviewPage: TaskReviewPage;
  Agreement: Agreement;
  RequestDecisionResult: RequestDecisionResult;
  CollaborationRequestPage: CollaborationRequestPage;
  TaskPage: TaskPage;
  Task: Task;
  RequestDecisionInput: RequestDecisionInput;
  CollaborationRequest: CollaborationRequest;
  TaskHandoffActions: TaskHandoffActions;
  Handoff: Handoff;
  AgentRun: AgentRun;
  ApprovalDecisionInput: ApprovalDecisionInput;
  Approval: Approval;
  Artifact: Artifact;
  EntityReference: EntityReference;
  ProjectionPayload: ProjectionPayload;
  ProjectionEnvelope: ProjectionEnvelope;
  StreamSnapshot: StreamSnapshot;
  StreamEvents: StreamEvents;
  WsHello: WsHello;
  WsSubscribe: WsSubscribe;
  WsAck: WsAck;
  WsWelcome: WsWelcome;
  WsSubscribed: WsSubscribed;
  WsControl: WsControl;
  WsHeartbeat: WsHeartbeat;
  WsClientFrame: WsClientFrame;
  WsServerFrame: WsServerFrame;
}
export interface OrganizationInvitationPreview {
  invitation_id: Identifier;
  tenant_id: Identifier;
  tenant_name: string;
  workspace_id: Identifier;
  workspace_name: string;
  role: 'member' | 'guest';
  status: 'pending' | 'accepted';
  expires_at: UtcTimestamp;
}
export interface OrganizationInvitation {
  id: Identifier;
  principal_id: Identifier;
  workspace_id: Identifier;
  role: 'member' | 'guest';
  status: 'pending' | 'accepted' | 'revoked' | 'expired';
  version: Version;
  expires_at: UtcTimestamp;
  created_by: Identifier;
}
export interface OrganizationInvitationPage {
  /**
   * @maxItems 100
   */
  items: OrganizationInvitation[];
  next_cursor?: Cursor;
}
export interface CreateOrganizationInvitationInput {
  principal_id: Identifier;
  workspace_id: Identifier;
  role: 'member' | 'guest';
  expires_in_hours: number;
  reason: string;
}
export interface CreatedOrganizationInvitation {
  invitation: OrganizationInvitation;
  code?: string;
}
export interface RevokeOrganizationInvitationInput {
  reason: string;
}
export interface AcceptOrganizationInvitationInput {
  code: string;
}
export interface AcceptedOrganizationInvitation {
  invitation_id: Identifier;
  tenant_id: Identifier;
  workspace_id: Identifier;
}
export interface ManagedTenantMember {
  principal: Principal;
  role: 'owner' | 'admin' | 'member' | 'guest' | 'agent';
  status: 'active' | 'disabled' | 'historical';
  version: Version;
}
export interface Principal {
  id: Identifier;
  kind: 'human' | 'agent' | 'service';
  display_name: string;
  status: 'active' | 'disabled' | 'deleted';
}
export interface ManagedTenantMemberPage {
  /**
   * @maxItems 100
   */
  items: ManagedTenantMember[];
  next_cursor?: Cursor;
}
export interface SetTenantMemberInput {
  role: 'owner' | 'admin' | 'member' | 'guest';
  status: 'active' | 'disabled';
  reason: string;
}
export interface OrganizationManagementAccess {
  can_manage: boolean;
}
export interface ManagedWorkspace {
  id: Identifier;
  name: string;
  version: Version;
}
export interface ManagedWorkspacePage {
  /**
   * @maxItems 100
   */
  items: ManagedWorkspace[];
  next_cursor?: Cursor;
}
export interface OrganizationCandidate {
  principal: Principal;
  tenant_role: 'owner' | 'admin' | 'member' | 'guest';
}
export interface OrganizationCandidatePage {
  /**
   * @maxItems 100
   */
  items: OrganizationCandidate[];
  next_cursor?: Cursor;
}
export interface ManagedWorkspaceMember {
  principal: Principal;
  role: 'admin' | 'member' | 'guest';
  status: 'active' | 'disabled';
  version: Version;
  tenant_status: 'active' | 'disabled' | 'historical';
}
export interface ManagedWorkspaceMemberPage {
  /**
   * @maxItems 100
   */
  items: ManagedWorkspaceMember[];
  next_cursor?: Cursor;
}
export interface CreateManagedWorkspaceInput {
  name: string;
}
export interface SetWorkspaceMemberInput {
  principal_id: Identifier;
  role: 'admin' | 'member' | 'guest';
  status: 'active' | 'disabled';
  reason: string;
}
export interface MemorySourceRef {
  kind: 'message' | 'task' | 'artifact_version';
  id: Identifier;
  version: Version;
  sha256: string;
}
export interface CreateMemoryInput {
  scope: 'personal' | 'conversation' | 'task';
  conversation_id?: Identifier;
  task_id?: Identifier;
  body: string;
  /**
   * @maxItems 20
   */
  source_refs: MemorySourceRef[];
  confirmation: 'confirmed' | 'needs_confirmation' | 'conflicted';
  confidence: number;
  expires_at?: UtcTimestamp | null;
  status?: 'active' | 'disabled';
}
export interface UpdateMemoryInput {
  scope: 'personal' | 'conversation' | 'task';
  conversation_id?: Identifier;
  task_id?: Identifier;
  body: string;
  /**
   * @maxItems 20
   */
  source_refs: MemorySourceRef[];
  confirmation: 'confirmed' | 'needs_confirmation' | 'conflicted';
  confidence: number;
  expires_at?: UtcTimestamp | null;
  status: 'active' | 'disabled';
}
export interface ExplicitMemory {
  id: Identifier;
  created_by: Identifier;
  scope: 'personal' | 'conversation' | 'task';
  conversation_id: Identifier | null;
  task_id: Identifier | null;
  version: Version;
  body: string;
  sha256: string;
  /**
   * @maxItems 20
   */
  source_refs: MemorySourceRef[];
  confirmation: 'confirmed' | 'needs_confirmation' | 'conflicted';
  confidence: number;
  status: 'active' | 'disabled';
  expires_at: UtcTimestamp | null;
  created_at: UtcTimestamp;
  updated_at: UtcTimestamp;
  trust_level: 'user_content';
  instruction_authority: 'none';
}
export interface ExplicitMemoryPage {
  /**
   * @maxItems 50
   */
  items: ExplicitMemory[];
  next_cursor?: Cursor;
}
export interface MemoryDeletion {
  id: Identifier;
  deleted: true;
}
export interface KnowledgeSearchHit {
  kind: 'message' | 'task' | 'artifact_version' | 'memory';
  id: Identifier;
  version: Version;
  sha256: string;
  title: string;
  snippet: string;
  conversation_id: Identifier | null;
  task_id: Identifier | null;
  artifact_id?: Identifier;
  trust_level: 'user_content';
  instruction_authority: 'none';
}
export interface KnowledgeSearchPage {
  /**
   * @maxItems 50
   */
  items: KnowledgeSearchHit[];
  next_cursor?: Cursor;
}
export interface KnowledgeSearchQuery {
  q: string;
  kind?: 'message' | 'task' | 'artifact_version' | 'memory';
  workspace_id?: Identifier;
  conversation_id?: Identifier;
  task_id?: Identifier;
  cursor?: Cursor;
  limit?: number;
}
export interface RecoveryReasonInput {
  reason: string;
}
export interface RecoveryLookupInput {}
export interface RecoveryConfirmInput {
  evidence_id: Identifier;
  confirmed: true;
  reason: string;
}
export interface RecoveryUnfreezeInput {
  confirmed: true;
  reason: string;
  freeze_digest: string;
  journal_digest: string;
}
export interface RecoveryStatus {
  frozen: boolean;
  journal_frozen: boolean;
  database_frozen: boolean;
  revision: Version;
  open_cases: number;
  pending_operations: number;
  freeze_digest: string;
  journal_digest: string;
}
export interface RecoveryIntent {
  task_id: Identifier;
  fingerprint: string;
  business_key: IdempotencyKey;
  tool_id: string;
  tool_version: Version | null;
  target_id: string;
  currency: string;
  estimate_microunits: Counter;
  budget_account_ids: [Identifier, ...Identifier[]] | null;
  created_at: UtcTimestamp;
}
export interface RecoveryEvidence {
  id: Identifier;
  case_id: Identifier;
  intent_hash: string;
  evidence_hash: string;
  outcome: 'succeeded' | 'no_effect' | 'unknown';
  receipt_id: string | null;
  actual_microunits: Counter | null;
  reason: string | null;
  created_at: UtcTimestamp;
}
export interface RecoveryCase {
  id: Identifier;
  action_id: Identifier;
  attempt_id: Identifier;
  reason: string;
  status: 'open' | 'resolved';
  version: Version;
  intent: RecoveryIntent | null;
  /**
   * @maxItems 20
   */
  evidence: RecoveryEvidence[];
  created_at: UtcTimestamp;
  resolved_at: UtcTimestamp | null;
  resolved_by: Identifier | null;
}
export interface RecoveryCasePage {
  /**
   * @maxItems 100
   */
  items: RecoveryCase[];
  next_cursor?: Cursor;
}
export interface NotificationPushKey {
  enabled: boolean;
  public_key: string | null;
}
export interface NotificationSubscription {
  endpoint: string;
  keys: {
    p256dh: string;
    auth: string;
  };
}
export interface NotificationItem {
  id: Identifier;
  category: 'message' | 'task' | 'request' | 'action' | 'run';
  hint: '你有新的待查看事项';
  version: Version;
  unread: boolean;
  silent: boolean;
  created_at: UtcTimestamp;
  updated_at: UtcTimestamp;
}
export interface NotificationPage {
  /**
   * @maxItems 100
   */
  items: NotificationItem[];
  next_cursor?: Cursor;
}
export interface NotificationUnread {
  unread_count: number;
}
export interface NotificationLocation {
  notification_id: Identifier;
  version: Version;
  target: {
    type: 'message' | 'task' | 'request' | 'action' | 'run';
    id: Identifier;
    version: Version;
  };
  conversation_id: Identifier | null;
  task_id: Identifier | null;
}
export interface NotificationRead {
  id: Identifier;
  version: Version;
  read: true;
}
export interface NotificationPreferences {
  version: Version;
  categories: {
    message: boolean;
    task: boolean;
    request: boolean;
    action: boolean;
    run: boolean;
  };
  dnd: {
    enabled: boolean;
    time_zone: string;
    start: string;
    end: string;
  };
}
export interface NotificationPreferencesInput {
  categories: {
    message: boolean;
    task: boolean;
    request: boolean;
    action: boolean;
    run: boolean;
  };
  dnd: {
    enabled: boolean;
    time_zone: string;
    start: string;
    end: string;
  };
}
export interface NotificationMuteInput {
  muted: boolean;
}
export interface NotificationMute {
  conversation_id: Identifier;
  muted: boolean;
}
export interface NotificationDeviceInput {
  enabled: boolean;
}
export interface NotificationDevice {
  id: Identifier;
  enabled: boolean;
  version: Version;
}
export interface NotificationDevicePage {
  /**
   * @maxItems 100
   */
  items: NotificationDevice[];
}
export interface CreateExportInput {
  scope: 'conversation' | 'task' | 'personal';
  scope_id?: Identifier;
}
export interface ExportJob {
  id: Identifier;
  scope: 'conversation' | 'task' | 'personal';
  scope_id: Identifier | null;
  created_at: UtcTimestamp;
  expires_at: UtcTimestamp;
  format: 'imbox.ndjson.v1';
  consistency: 'live_authorized_reads';
  content_url: string;
}
export interface GovernancePolicy {
  message_days: number;
  resource_days: number;
  run_content_days: number;
  export_hours: 24;
  independent_ledger: boolean;
  scope: 'deployment';
  external_copies: 'not_recallable';
  offline_message_cache_allowed: boolean;
  offline_queue_allowed: boolean;
  offline_queue_max_days: 7;
  workspace_policy: 'inherits_deployment';
}
export interface CreateArtifactCommentInput {
  version_id: Identifier;
  sha256: string;
  anchor: ArtifactCommentAnchor;
  body: string;
}
export interface EditArtifactCommentInput {
  body: string;
}
export interface ArtifactComment {
  id: Identifier;
  artifact_id: Identifier;
  version_id: Identifier;
  sha256: string;
  anchor: ArtifactCommentAnchor;
  body: string;
  version: Version;
  created_by: Identifier;
  created_at: UtcTimestamp;
  updated_at: UtcTimestamp;
  deleted: boolean;
}
export interface ArtifactCommentPage {
  /**
   * @maxItems 100
   */
  items: ArtifactComment[];
  next_cursor?: Cursor;
}
export interface CreateArtifactShareInput {
  version_id: Identifier;
  sha256: string;
  recipient_principal_id?: Identifier;
  conversation_id?: Identifier;
  task_id?: Identifier;
  expires_at: UtcTimestamp;
}
export interface ArtifactShare {
  id: Identifier;
  artifact_id: Identifier;
  version_id: Identifier;
  sha256: string;
  title: string;
  filename: string;
  content_type: string;
  byte_size: number;
  created_by: Identifier;
  recipient_principal_id: Identifier | null;
  conversation_id: Identifier | null;
  task_id: Identifier | null;
  version: Version;
  expires_at: UtcTimestamp;
  created_at: UtcTimestamp;
  download_path: string;
}
export interface ArtifactShareRevocation {
  id: Identifier;
  revoked: true;
}
export interface ArtifactShareSummary {
  id: Identifier;
  artifact_id: Identifier;
  version_id: Identifier;
  version: Version;
  recipient_principal_id: Identifier | null;
  conversation_id: Identifier | null;
  task_id: Identifier | null;
  expires_at: UtcTimestamp;
  created_at: UtcTimestamp;
  status: 'active' | 'revoked';
}
export interface ArtifactSharePage {
  /**
   * @maxItems 100
   */
  items: ArtifactShareSummary[];
  next_cursor?: Cursor;
}
export interface ArtifactCommentDeletion {
  id: Identifier;
  deleted: true;
}
export interface PromoteRunInput {
  task: CreateTaskInput;
  confirm_new_authorization: true;
}
export interface CreateTaskInput {
  workspace_id: Identifier;
  title: string;
  goal: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  acceptance_criteria: [string, ...string[]];
  /**
   * @minItems 1
   * @maxItems 20
   */
  reviewer_principal_ids: [Identifier, ...Identifier[]];
  budget: InitialBudget;
  due_at?: UtcTimestamp;
  execution_deadline?: UtcTimestamp;
}
export interface InitialBudget {
  currency: string;
  limit_microunits: Counter;
}
export interface CursorOnlyQuery {
  cursor?: Cursor;
}
export interface TaskEscalation {
  id: Identifier;
  task_id: Identifier;
  task_version: Version;
  can_takeover: boolean;
  reason: 'owner_unavailable' | 'execution_deadline';
  assigned_to: Identifier | null;
  created_at: UtcTimestamp;
}
export interface TaskEscalationPage {
  /**
   * @maxItems 100
   */
  items: TaskEscalation[];
  next_cursor?: Cursor;
}
export interface CreateScheduleInput {
  task_id: Identifier;
  run_id: Identifier;
  timezone: string;
  trigger:
    | {
        kind: 'once';
      }
    | {
        kind: 'daily';
        local_time: string;
      };
  start_at: UtcTimestamp;
  deadline: UtcTimestamp;
  missed_policy: 'skip' | 'coalesce';
  maximum_wakeups: number;
}
export interface ReviseScheduleInput {
  task_id: Identifier;
  run_id: Identifier;
  timezone: string;
  trigger:
    | {
        kind: 'once';
      }
    | {
        kind: 'daily';
        local_time: string;
      };
  start_at: UtcTimestamp;
  deadline: UtcTimestamp;
  missed_policy: 'skip' | 'coalesce';
  maximum_wakeups: number;
  enabled: boolean;
}
export interface Schedule {
  id: Identifier;
  created_by: Identifier;
  task_id: Identifier;
  run_id: Identifier;
  timezone: string;
  trigger:
    | {
        kind: 'once';
      }
    | {
        kind: 'daily';
        local_time: string;
      };
  start_at: UtcTimestamp;
  deadline: UtcTimestamp;
  missed_policy: 'skip' | 'coalesce';
  maximum_wakeups: number;
  overlap_policy: 'forbid';
  status: 'enabled' | 'disabled' | 'completed' | 'expired';
  revision: Version;
  version: Version;
  occurrences_created: number;
  missed_count: number;
  next_at: UtcTimestamp | null;
  created_at: UtcTimestamp;
  updated_at: UtcTimestamp;
}
export interface ScheduleList {
  /**
   * @maxItems 100
   */
  items: Schedule[];
  next_cursor?: Cursor;
}
export interface ScheduleOccurrence {
  id: Identifier;
  schedule_id: Identifier;
  schedule_revision: Version;
  scheduled_instant: UtcTimestamp;
  timezone: string;
  status: 'pending' | 'dispatched' | 'skipped' | 'denied';
  reason: string | null;
  causal_root_id: Identifier;
  trigger_id: Identifier;
  depth: 0;
  created_at: UtcTimestamp;
  resolved_at: UtcTimestamp | null;
}
export interface ScheduleOccurrenceList {
  /**
   * @maxItems 100
   */
  items: ScheduleOccurrence[];
  next_cursor?: Cursor;
}
export interface ResourceScopeQuery {
  task_id?: Identifier;
  conversation_id?: Identifier;
  cursor?: Cursor;
  limit?: number;
}
export interface StoredResourcePage {
  /**
   * @maxItems 200
   */
  items: StoredResource[];
  next_cursor?: Cursor;
}
export interface StoredResource {
  id: Identifier;
  filename: string;
  content_type: string;
  byte_size: number;
  sha256: string;
  version: Version;
  conversation_id: Identifier | null;
  task_id: Identifier | null;
  created_by: Identifier;
  created_at: UtcTimestamp;
  download_path: string;
}
export interface StoredArtifactPage {
  /**
   * @maxItems 200
   */
  items: StoredArtifact[];
  next_cursor?: Cursor;
}
export interface StoredArtifact {
  can_append_version?: boolean;
  id: Identifier;
  title: string;
  kind: 'text' | 'markdown' | 'file';
  version: Version;
  head_version: Version;
  version_id: Identifier;
  resource: StoredResource;
  created_by: Identifier;
  created_at: UtcTimestamp;
}
export interface CreateUploadInput {
  conversation_id?: Identifier;
  task_id?: Identifier;
  filename: string;
  content_type: 'text/plain' | 'text/markdown' | 'application/json';
  byte_size: number;
  sha256: string;
}
export interface UploadTicket {
  id: Identifier;
  resource_id: Identifier;
  upload_url: string;
  upload_headers: {
    [k: string]: string;
  };
  expires_at: UtcTimestamp;
  max_bytes: number;
}
export interface CreateStoredArtifactInput {
  resource_id: Identifier;
  title: string;
}
export interface CreateArtifactBranchInput {
  base_version_id: Identifier;
  resource_id: Identifier;
}
export interface MergeArtifactBranchInput {
  branch_id: Identifier;
  resource_id: Identifier;
}
export interface ArtifactBranch {
  id: Identifier;
  artifact_id: Identifier;
  base_version_id: Identifier;
  resource: StoredResource;
  created_by: Identifier;
  created_at: UtcTimestamp;
  status: 'open' | 'merged';
  merged_version_id: Identifier | null;
  merged_against_version_id: Identifier | null;
  merged_by: Identifier | null;
}
export interface ArtifactBranchPage {
  /**
   * @maxItems 200
   */
  items: ArtifactBranch[];
  next_cursor?: Cursor;
}
export interface CreateStoredArtifactVersionInput {
  resource_id: Identifier;
}
export interface StoredArtifactVersion {
  id: Identifier;
  artifact_id: Identifier;
  version: Version;
  resource: StoredResource;
  created_by: Identifier;
  created_at: UtcTimestamp;
}
export interface StoredArtifactVersionPage {
  /**
   * @maxItems 200
   */
  items: StoredArtifactVersion[];
  next_cursor?: Cursor;
}
export interface ResourceDeletion {
  id: Identifier;
  deleted: true;
}
export interface AgentManagementAccess {
  can_manage: boolean;
}
export interface AgentCredentialPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: AgentCredential[];
  next_cursor?: Cursor;
}
export interface AgentCredential {
  id: Identifier;
  installation_id: Identifier;
  /**
   * @minItems 1
   * @maxItems 16
   */
  scopes: [
    (
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    ),
    ...(
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    )[],
  ];
  status: 'active' | 'revoked';
  revision: Version;
  expires_at: UtcTimestamp;
}
export interface AgentDeliveryInput {
  proposal_version: Version;
}
export interface AgentDeliveryReceipt {
  request_id: Identifier;
  proposal_version: Version;
  received_at: UtcTimestamp;
}
export interface RegisterAgentInput {
  workspace_id: Identifier;
  display_name: string;
  mode: 'hosted' | 'external';
  /**
   * @minItems 1
   * @maxItems 16
   */
  scopes: [
    (
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    ),
    ...(
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    )[],
  ];
  /**
   * @minItems 0
   * @maxItems 100
   */
  capabilities: string[];
  config: {
    model_alias?: 'local';
  };
}
export interface RegisteredAgent {
  id: Identifier;
  principal_id: Identifier;
  display_name: string;
  mode: 'hosted' | 'device' | 'external';
  status: 'active' | 'disabled';
  revision: Version;
  version: Version;
  /**
   * @minItems 0
   * @maxItems 16
   */
  scopes: (
    | 'agents.read'
    | 'knowledge.read'
    | 'knowledge.search'
    | 'messages.read'
    | 'messages.write'
    | 'tasks.read'
    | 'tasks.create'
    | 'tasks.write'
    | 'requests.read'
    | 'requests.ack'
    | 'requests.decide'
    | 'runs.create'
    | 'runs.read'
    | 'runs.execute'
    | 'runs.report'
    | 'runs.tools'
  )[];
  /**
   * @minItems 0
   * @maxItems 100
   */
  capabilities: string[];
}
export interface AgentDirectory {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: RegisteredAgent[];
}
export interface AgentDirectoryQuery {
  workspace_id: Identifier;
}
export interface IssueAgentCredentialInput {
  /**
   * @minItems 1
   * @maxItems 16
   */
  scopes: [
    (
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    ),
    ...(
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    )[],
  ];
  lifetime_seconds: number;
}
export interface IssuedAgentCredential {
  credential: AgentCredential;
  secret: string | null;
  secret_returned: boolean;
}
export interface MachineTokenInput {
  credential: string;
  /**
   * @minItems 1
   * @maxItems 16
   */
  scopes: [
    (
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    ),
    ...(
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    )[],
  ];
}
export interface MachineToken {
  access_token: string;
  token_type: 'Bearer';
  expires_at: UtcTimestamp;
  /**
   * @minItems 1
   * @maxItems 16
   */
  scopes: [
    (
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    ),
    ...(
      | 'agents.read'
      | 'knowledge.read'
      | 'knowledge.search'
      | 'messages.read'
      | 'messages.write'
      | 'tasks.read'
      | 'tasks.create'
      | 'tasks.write'
      | 'requests.read'
      | 'requests.ack'
      | 'requests.decide'
      | 'runs.create'
      | 'runs.read'
      | 'runs.execute'
      | 'runs.report'
      | 'runs.tools'
    )[],
  ];
}
export interface MachineLease {
  run_id: Identifier;
  generation: Version;
}
export interface MachineClaim {
  lease: MachineLease | null;
}
export interface MachineHeartbeatInput {
  generation: Version;
}
export interface MachineHeartbeat {
  expires_at: UtcTimestamp;
  cancellation_requested: boolean;
  pause_requested: boolean;
}
export interface MachineCancellationAckInput {
  generation: Version;
}
export interface MachineCancellationAck {
  run_id: Identifier;
  generation: Version;
  acknowledged_at: UtcTimestamp;
  report_source: 'external_report';
}
export interface MachineReportInput {
  generation: Version;
  status:
    | 'running'
    | 'waiting_input'
    | 'waiting_approval'
    | 'waiting_dependency'
    | 'paused'
    | 'completed'
    | 'failed'
    | 'cancelled';
  checkpoint: {
    [k: string]: unknown;
  };
  summary?: string;
  output?: string;
}
export interface MachineRunPage {
  /**
   * @minItems 0
   * @maxItems 100
   */
  items: RuntimeRun[];
}
export interface RuntimeRun {
  id: Identifier;
  execution_location: 'hosted' | 'device' | 'external';
  report_source: 'platform_verified' | 'external_report';
  agent_id: Identifier;
  agent_revision: Version;
  task_id: Identifier | null;
  conversation_id: Identifier | null;
  status:
    | 'queued'
    | 'running'
    | 'waiting_input'
    | 'waiting_approval'
    | 'waiting_dependency'
    | 'paused'
    | 'cancelling'
    | 'completed'
    | 'failed'
    | 'cancelled'
    | 'expired';
  version: Version;
  lease_generation: Counter;
  cancellation_acknowledged_at?: UtcTimestamp | null;
  cancellation_requested: boolean;
  pause_requested: boolean;
  context_manifest_id: Identifier;
  tool_grant_id: Identifier | null;
  summary: string;
  output: string | null;
  budget: RuntimeBudget;
  created_at: UtcTimestamp;
  updated_at: UtcTimestamp;
}
export interface RuntimeBudget {
  currency: string;
  limit_microunits: Counter;
  reserved_microunits: Counter;
  spent_microunits: Counter;
  blocked: boolean;
}
export interface ActionParameters {
  text: string;
}
export interface CreateGrantInput {
  task_id: Identifier;
  executor_principal_id: Identifier;
  tool_id: string;
  tool_version: Version;
  target_id: string;
  allow_execute: boolean;
  allow_disclosure: boolean;
  /**
   * @minItems 0
   * @maxItems 20
   */
  resource_versions: TaskVersionRef[];
  /**
   * @minItems 1
   * @maxItems 20
   */
  approver_principal_ids: [Identifier, ...Identifier[]];
  budget: InitialBudget;
  expires_at: UtcTimestamp;
}
export interface TaskVersionRef {
  type: 'task';
  id: Identifier;
  version: Version;
}
export interface CapabilityGrant {
  id: Identifier;
  task_id: Identifier;
  executor_principal_id: Identifier;
  issued_by: Identifier;
  tool_id: string;
  tool_version: Version;
  target_id: string;
  allow_execute: boolean;
  allow_disclosure: boolean;
  /**
   * @minItems 0
   * @maxItems 20
   */
  resource_versions: TaskVersionRef[];
  /**
   * @minItems 0
   * @maxItems 20
   */
  approver_principal_ids: Identifier[];
  budget: InitialBudget;
  status: 'active' | 'revoked';
  revision: Version;
  expires_at: UtcTimestamp;
  created_at: UtcTimestamp;
}
export interface CapabilityGrantPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: CapabilityGrant[];
}
export interface CreateActionInput {
  task_id: Identifier;
  grant_id: Identifier;
  executor_principal_id: Identifier;
  tool_id: string;
  tool_version: Version;
  target_id: string;
  parameters: ActionParameters;
  /**
   * @minItems 0
   * @maxItems 20
   */
  resource_versions: TaskVersionRef[];
  business_key: IdempotencyKey;
  estimate: InitialBudget;
  required?: boolean;
}
export interface ReviseActionInput {
  parameters: ActionParameters;
  /**
   * @minItems 0
   * @maxItems 20
   */
  resource_versions: TaskVersionRef[];
}
export interface ActionApprovalDecisionInput {
  decision: 'approve' | 'reject';
  action_version: Version;
  fingerprint: string;
  comment: string;
}
export interface ActionApproval {
  id: Identifier;
  action_id: Identifier;
  action_version: Version;
  fingerprint: string;
  target_id: string;
  status: 'pending' | 'approved' | 'rejected' | 'revoked';
  expires_at: UtcTimestamp;
  decided_by?: Identifier;
  consumed: boolean;
}
export interface Action {
  id: Identifier;
  task_id: Identifier;
  requester_id: Identifier;
  executor_id: Identifier;
  grant_id: Identifier;
  grant_revision: Version;
  tool_id: string;
  tool_version: Version;
  target_id: string;
  parameters: ActionParameters;
  /**
   * @minItems 0
   * @maxItems 20
   */
  resource_versions: TaskVersionRef[];
  business_key: IdempotencyKey;
  fingerprint: string;
  status:
    | 'proposed'
    | 'awaiting_approval'
    | 'ready'
    | 'executing'
    | 'succeeded'
    | 'failed'
    | 'unknown'
    | 'cancelled';
  version: Version;
  approval_binding_version: Version;
  approval_required: boolean;
  required: boolean;
  attempt_count: number;
  estimate: InitialBudget;
  approval?: ActionApproval;
  created_at: UtcTimestamp;
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface ActionPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: Action[];
  next_cursor?: Cursor;
}
export interface ActionReconcileInput {
  reason: string;
}
export interface ActionReconciliation {
  action: Action;
  outcome: 'succeeded' | 'no_effect' | 'unknown' | 'conflict';
}
export interface MachineToolIntentInput {
  generation: Version;
  text: string;
}
export interface MachineToolExecuteInput {
  generation: Version;
}
export interface RuntimeRunPage {
  /**
   * @maxItems 100
   */
  items: RuntimeRun[];
  next_cursor?: Cursor;
}
export interface RuntimeRunListQuery {
  task_id?: Identifier;
  conversation_id?: Identifier;
  cursor?: Cursor;
  limit?: number;
}
export interface InstallRuntimeAgentInput {
  principal_id: Identifier;
  revision: Version;
  mode: 'hosted' | 'device' | 'external';
  config: {
    [k: string]: unknown;
  };
  /**
   * @maxItems 100
   */
  capabilities: string[];
}
export interface RuntimeAgentInstallation {
  id: Identifier;
  principal_id: Identifier;
  revision: Version;
  mode: 'hosted' | 'device' | 'external';
}
export interface CreateRuntimeRunInput {
  agent_id: Identifier;
  agent_revision: Version;
  task_id?: Identifier;
  conversation_id?: Identifier;
  previous_run_id?: Identifier;
  tool_grant_id?: Identifier;
  /**
   * @maxItems 50
   */
  context: RuntimeSourceReference[];
  purpose: string;
  destination: string;
  budget: InitialBudget;
}
export interface RuntimeContextItem {
  ordinal: number;
  source_type: 'message' | 'task' | 'memory' | 'artifact_version';
  source_id: Identifier;
  source_version: Version;
  source_sha256: string | null;
  content_hash: string;
  required: boolean;
  trust_level: 'untrusted_user_content';
  payload: {
    [k: string]: unknown;
  };
  authorization_snapshot: {
    [k: string]: unknown;
  };
}
export interface RuntimeContextManifest {
  id: Identifier;
  purpose: string;
  destination: string;
  content_hash: string;
  total_bytes: number;
  /**
   * @maxItems 50
   */
  items: RuntimeContextItem[];
}
export interface PaginationQuery {
  cursor?: Cursor;
  limit?: number;
}
export interface ResourceParams {
  id: Identifier;
}
export interface ProjectionContext {
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface Workspace {
  id: Identifier;
  name: string;
  role: 'owner' | 'admin' | 'member' | 'guest';
}
export interface WorkspacePage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: Workspace[];
}
export interface DevLoginInput {
  principal_id: Identifier;
}
export interface DevLoginResult {
  session_id: Identifier;
  principal_id: Identifier;
  csrf_token: string;
  expires_at: UtcTimestamp;
}
export interface Session {
  id: Identifier;
  created_at: UtcTimestamp;
  expires_at: UtcTimestamp;
  revoked_at: UtcTimestamp | null;
  revision: Version;
}
export interface Account {
  principal: Principal;
  csrf_token: string;
  session_id: Identifier;
  session_expires_at: UtcTimestamp;
}
export interface Me {
  principal: Principal;
  tenant_id: Identifier;
  csrf_token: string;
  authz_revision: Version;
  session_id: Identifier;
  session_expires_at: UtcTimestamp;
  /**
   * @minItems 0
   * @maxItems 200
   */
  workspaces: Workspace[];
  /**
   * @minItems 0
   * @maxItems 200
   */
  capabilities: string[];
}
export interface WorkspaceMemberPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: {
    principal: Principal;
    role: 'admin' | 'member' | 'guest';
  }[];
}
export interface ConversationMemberPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: {
    principal: Principal;
    role: 'owner' | 'admin' | 'member';
  }[];
}
export interface AddConversationMemberInput {
  principal_id: Identifier;
  role?: 'admin' | 'member';
}
export interface ReactionInput {
  emoji: '👍' | '❤️' | '🎉' | '😄' | '👀' | '🙏';
}
export interface MessageReactionSummary {
  emoji: string;
  count: Counter;
}
export interface MessageQuote {
  source_id: Identifier;
  source_version: Version;
  body: string | null;
  unavailable: boolean;
}
export interface ReactionPage {
  next_cursor?: Cursor;
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: {
    id: Identifier;
    message_id: Identifier;
    principal_id: Identifier;
    emoji: string;
  }[];
}
export interface ReadCursorInput {
  last_read_seq: Counter;
}
export interface ReadCursor {
  last_read_seq: Counter;
}
export interface Error {
  code:
    | 'UNAUTHENTICATED'
    | 'FORBIDDEN'
    | 'DISCLOSURE_DENIED'
    | 'NOT_FOUND'
    | 'VALIDATION_FAILED'
    | 'VERSION_CONFLICT'
    | 'IDEMPOTENCY_CONFLICT'
    | 'REQUEST_EXPIRED'
    | 'RESYNC_REQUIRED'
    | 'BUDGET_EXCEEDED'
    | 'DEPENDENCY_BLOCKED'
    | 'INVALID_STATE_TRANSITION'
    | 'ACCEPTANCE_REQUIRED'
    | 'TASK_TERMINATED'
    | 'PROPOSAL_VERSION_CONFLICT'
    | 'DEPENDENCY_CYCLE'
    | 'EXECUTION_FENCE_CONFLICT'
    | 'OWNER_CONFLICT'
    | 'LEASE_CONFLICT'
    | 'LEASE_EXPIRED'
    | 'LEASE_NOT_EXPIRED'
    | 'RETRY_NOT_SAFE'
    | 'RETRY_EXHAUSTED'
    | 'BUDGET_BLOCKED'
    | 'USAGE_CONFLICT'
    | 'RESERVATION_NOT_FOUND'
    | 'CHARGE_STATUS_UNKNOWN'
    | 'CONTENT_REJECTED'
    | 'CAPACITY_EXCEEDED'
    | 'HANDOFF_ACTIONS_CHANGED'
    | 'HANDOFF_ACTIONS_LIMIT'
    | 'LAST_WORKSPACE_ADMIN'
    | 'STEP_LIMIT_EXCEEDED'
    | 'EXECUTION_EXPIRED'
    | 'RATE_LIMITED'
    | 'ACTION_OUTCOME_UNKNOWN'
    | 'SERVICE_UNAVAILABLE'
    | 'INTERNAL_ERROR';
  message: string;
  request_id: string;
  retryable: boolean;
  details?: {
    current_version?: Version;
    /**
     * @minItems 0
     * @maxItems 32
     */
    fields?: string[];
    retry_after_seconds?: number;
  };
}
export interface CreateConversationInput {
  workspace_id: Identifier;
  kind: 'direct' | 'group';
  title?: string;
  /**
   * @minItems 1
   * @maxItems 100
   */
  member_ids: [Identifier, ...Identifier[]];
  history_policy?: 'since_join' | 'all';
}
export interface Conversation {
  id: Identifier;
  workspace_id: Identifier;
  kind: 'direct' | 'group';
  title: string;
  version: Version;
  created_at: UtcTimestamp;
  history_policy: 'since_join' | 'all';
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface CreateMessageInput {
  client_message_id: Identifier;
  body: string;
  format?: 'text' | 'markdown';
  /**
   * @minItems 0
   * @maxItems 10
   */
  attachment_ids?: Identifier[];
  reply_to_id?: Identifier;
  reply_to_version?: Version;
  thread_root_id?: Identifier;
}
export interface EditMessageInput {
  body: string;
  format?: 'text' | 'markdown';
}
export interface Message {
  id: Identifier;
  conversation_id: Identifier;
  client_message_id: Identifier;
  actor: Principal;
  version: Version;
  seq: Counter;
  body: string;
  format: 'text' | 'markdown';
  /**
   * @minItems 0
   * @maxItems 10
   */
  attachment_ids: Identifier[];
  reply_to_id?: Identifier;
  reply_to_version?: Version;
  thread_root_id?: Identifier;
  created_at: UtcTimestamp;
  edited_at?: UtcTimestamp;
  deleted: boolean;
  quote?: MessageQuote;
  /**
   * @minItems 0
   * @maxItems 6
   */
  reactions?: MessageReactionSummary[];
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface ConversationPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: Conversation[];
  next_cursor?: Cursor;
}
export interface MessagePage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: Message[];
  next_cursor?: Cursor;
}
export interface Budget {
  currency: string;
  limit_microunits: Counter;
  reserved_microunits: Counter;
  spent_microunits: Counter;
}
export interface TextEvidenceInput {
  type: 'text';
  text: string;
  /**
   * @minItems 0
   * @maxItems 20
   */
  source_refs: TaskVersionRef[];
}
export interface ArtifactEvidenceRef {
  type: 'artifact_version';
  artifact_id: Identifier;
  version_id: Identifier;
  sha256: string;
}
export interface TextEvidence {
  type: 'text';
  id: Identifier;
  text: string;
  /**
   * @minItems 0
   * @maxItems 20
   */
  source_refs: TaskVersionRef[];
  sha256: string;
}
export interface UpdateTaskInput {
  title?: string;
  goal?: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  acceptance_criteria?: [string, ...string[]];
  archived?: boolean;
  due_at?: UtcTimestamp;
}
export interface TaskParticipantInput {
  principal_id: Identifier;
  role: 'contributor' | 'reviewer' | 'observer';
}
export interface TaskParticipantPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: {
    principal_id: Identifier;
    role: 'owner' | 'contributor' | 'reviewer' | 'observer';
    version: Version;
  }[];
}
export interface TaskReasonInput {
  reason: string;
}
export interface ReopenTaskInput {
  reason: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  acceptance_criteria: [string, ...string[]];
}
export interface TaskStateInput {
  state: 'active' | 'blocked' | 'resume' | 'failed';
  reason?: string;
}
export interface TaskConversationLinkInput {
  conversation_id: Identifier;
  public_summary: string;
}
export interface TaskSummary {
  task_id: Identifier;
  conversation_id: Identifier;
  public_summary: string;
  version: Version;
}
export interface TaskSummaryPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: TaskSummary[];
}
export interface TaskDependencyInput {
  prerequisite_task_id: Identifier;
}
export interface WorkProposal {
  title: string;
  goal: string;
  /**
   * @minItems 0
   * @maxItems 20
   */
  inputs: EvidenceInput[];
  deliverable_schema: 'imbox.text-evidence.v1';
  acceptance: {
    /**
     * @minItems 1
     * @maxItems 20
     */
    criteria: [string, ...string[]];
    /**
     * @minItems 1
     * @maxItems 20
     */
    reviewer_principal_ids: [Identifier, ...Identifier[]];
  };
  budget: InitialBudget;
  due_at?: UtcTimestamp;
  execution_deadline?: UtcTimestamp;
  /**
   * @minItems 0
   * @maxItems 0
   */
  allowed_actions: [];
  disclosure: {
    scope: 'request_recipients';
    summary: string;
  };
  /**
   * @minItems 0
   * @maxItems 50
   */
  dependencies: Identifier[];
  cancellation_rule: 'owner_or_accountable';
  escalation_principal_id: Identifier;
  handoff?: {
    completed_summary: string;
    pending_summary: string;
    /**
     * @minItems 0
     * @maxItems 100
     */
    pending_action_ids: Identifier[];
  };
}
export interface CreateTaskRequestInput {
  kind: 'consult' | 'review' | 'delegate' | 'handoff';
  recipient_principal_id: Identifier;
  proposal: WorkProposal;
  request_expires_at: UtcTimestamp;
}
export interface ReviseTaskRequestInput {
  proposal: WorkProposal;
  request_expires_at: UtcTimestamp;
  expected_task_version: Version;
}
export interface SubmissionInput {
  goal_version: Version;
  summary: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  evidence: [EvidenceInput, ...EvidenceInput[]];
}
export interface Submission {
  id: Identifier;
  task_id: Identifier;
  submitted_by: Identifier;
  goal_version: Version;
  execution_epoch: Version;
  summary: string;
  /**
   * @minItems 1
   * @maxItems 20
   */
  evidence: [Evidence, ...Evidence[]];
  created_at: UtcTimestamp;
}
export interface SubmissionPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: Submission[];
}
export interface TaskReviewInput {
  submission_id: Identifier;
  decision: 'accept' | 'return';
  comment: string;
}
export interface TaskReview {
  id: Identifier;
  task_id: Identifier;
  submission_id: Identifier;
  reviewer_id: Identifier;
  decision: 'accept' | 'return';
  comment: string;
  goal_version: Version;
  execution_epoch: Version;
  created_at: UtcTimestamp;
}
export interface TaskReviewPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: TaskReview[];
}
export interface Agreement {
  id: Identifier;
  request_id: Identifier;
  task_id: Identifier;
  accepted_by: Identifier;
  accepted_version: Version;
  terms: WorkProposal;
  child_task_id?: Identifier;
  created_at: UtcTimestamp;
}
export interface RequestDecisionResult {
  request: CollaborationRequest;
  agreement?: Agreement;
}
export interface CollaborationRequest {
  received_at?: UtcTimestamp | null;
  id: Identifier;
  task_id: Identifier;
  kind: 'consult' | 'review' | 'delegate' | 'handoff';
  proposer_id: Identifier;
  recipient_id: Identifier;
  proposal_version: Version;
  version: Version;
  expected_task_version: Version;
  execution_epoch: Version;
  goal_version: Version;
  proposal: WorkProposal;
  status:
    | 'pending'
    | 'clarification_requested'
    | 'accepted'
    | 'rejected'
    | 'cancelled'
    | 'expired'
    | 'superseded';
  goal: string;
  request_expires_at: UtcTimestamp;
  created_at: UtcTimestamp;
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface CollaborationRequestPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: CollaborationRequest[];
  next_cursor?: Cursor;
}
export interface TaskPage {
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: Task[];
  next_cursor?: Cursor;
}
export interface Task {
  id: Identifier;
  workspace_id: Identifier;
  root_task_id: Identifier;
  parent_task_id?: Identifier;
  title: string;
  goal_version: Version;
  /**
   * @minItems 0
   * @maxItems 20
   */
  reviewer_principal_ids: Identifier[];
  goal: string;
  owner_principal_id: Identifier;
  accountable_principal_id: Identifier;
  status: 'open' | 'active' | 'blocked' | 'in_review' | 'completed' | 'failed' | 'cancelled';
  archived: boolean;
  version: Version;
  execution_epoch: Version;
  created_at: UtcTimestamp;
  due_at?: UtcTimestamp;
  /**
   * @minItems 0
   * @maxItems 20
   */
  acceptance_criteria: string[];
  budget: Budget;
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface RequestDecisionInput {
  decision: 'accept' | 'reject' | 'clarify';
  proposal_version: Version;
  expected_task_version: Version;
  comment?: string;
}
export interface TaskHandoffActions {
  task_id: Identifier;
  task_version: Version;
  /**
   * @minItems 0
   * @maxItems 100
   */
  pending_action_ids: Identifier[];
}
export interface Handoff {
  request_id: Identifier;
  task_id: Identifier;
  from_owner_id: Identifier;
  to_owner_id: Identifier;
  status:
    | 'pending'
    | 'clarification_requested'
    | 'accepted'
    | 'rejected'
    | 'cancelled'
    | 'expired'
    | 'superseded';
  proposal_version: Version;
  expected_task_version: Version;
  summary: string;
  /**
   * @minItems 0
   * @maxItems 100
   */
  pending_action_ids: Identifier[];
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface AgentRun {
  id: Identifier;
  agent_id: Identifier;
  agent_revision: Version;
  task_id?: Identifier;
  conversation_id?: Identifier;
  version: Version;
  lease_generation: Version;
  status:
    | 'queued'
    | 'running'
    | 'waiting_input'
    | 'waiting_approval'
    | 'waiting_dependency'
    | 'paused'
    | 'completed'
    | 'failed'
    | 'cancelling'
    | 'cancelled'
    | 'expired';
  execution_location: 'hosted' | 'device' | 'external';
  report_source: 'platform_verified' | 'external_report';
  created_at: UtcTimestamp;
  summary: string;
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface ApprovalDecisionInput {
  decision: 'approve' | 'reject';
  action_version: Version;
  comment?: string;
}
export interface Approval {
  id: Identifier;
  action_id: Identifier;
  action_version: Version;
  requester_id: Identifier;
  executor_id: Identifier;
  summary: string;
  status: 'pending' | 'approved' | 'rejected' | 'expired' | 'revoked';
  expires_at: UtcTimestamp;
  created_at: UtcTimestamp;
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface Artifact {
  id: Identifier;
  version_id: Identifier;
  version: Version;
  kind: 'text' | 'markdown' | 'image' | 'file' | 'code_patch';
  title: string;
  content_resource_id: Identifier;
  created_by: Identifier;
  created_at: UtcTimestamp;
  /**
   * @minItems 0
   * @maxItems 100
   */
  source_ids: Identifier[];
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
}
export interface EntityReference {
  type: 'conversation' | 'message' | 'task' | 'request' | 'agent_run' | 'approval' | 'artifact';
  id: Identifier;
  version: Version;
}
export interface ProjectionPayload {
  summary: string;
  status?: string;
  resource_ref?: Identifier;
  approval_ref?: Identifier;
  message?: Message;
  conversation?: Conversation;
}
export interface ProjectionEnvelope {
  type: 'projection.upsert' | 'projection.remove';
  protocol_version: 1;
  stream_id: Identifier;
  view_scope: Identifier;
  authz_generation: Version;
  projection_id: Identifier;
  projection_revision: Version;
  event_id: Identifier;
  entity: EntityReference;
  cursor: Cursor;
  schema_version: 1;
  payload: ProjectionPayload;
}
export interface StreamSnapshot {
  stream_id: Identifier;
  view_scope: Identifier;
  authz_generation: Version;
  snapshot_id: Identifier;
  window?: 'recent';
  history_truncated?: boolean;
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: ProjectionEnvelope[];
  cursor: Cursor;
  next_cursor?: Cursor;
  complete: boolean;
}
export interface StreamEvents {
  stream_id: Identifier;
  view_scope: Identifier;
  authz_generation: Version;
  /**
   * @minItems 0
   * @maxItems 200
   */
  items: ProjectionEnvelope[];
  cursor: Cursor;
  has_more: boolean;
}
export interface WsHello {
  type: 'hello';
  protocol_version: 1;
  client_id: Identifier;
}
export interface WsSubscribe {
  type: 'subscribe';
  stream_id: Identifier;
  cursor?: Cursor;
}
export interface WsAck {
  type: 'ack';
  stream_id: Identifier;
  cursor: Cursor;
}
export interface WsWelcome {
  type: 'welcome';
  protocol_version: 1;
  connection_id: Identifier;
  heartbeat_seconds: number;
}
export interface WsSubscribed {
  type: 'subscribed';
  stream_id: Identifier;
  authz_generation: Version;
  cursor: Cursor;
}
export interface WsControl {
  type: 'resync_required' | 'access_revoked';
  stream_id: Identifier;
  reason: 'cursor_expired' | 'authorization_changed' | 'unsupported_schema' | 'slow_consumer';
}
export interface WsHeartbeat {
  type: 'ping' | 'pong';
  nonce: string;
}
